name: Secret Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  secret-scan:
    name: Scan for Secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz \
            | tar xz -C /usr/local/bin

      - name: Run secret scan
        run: |
          gitleaks detect --source . --exit-code 1